language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "u3jBCY2Eux6H4gxnfkz6EqRLzPPLSDNDUUPTWMzY+jO/cQcOmnMiN88VXZ6Rs3X1PVOVsYrSb0JzetX4QJ5G9px6UCIX7ewtDhm8A/BSPzRmkdNLVnH5z+Cqc6yx4Tw6ZxunoKA/ZRefyDMkJBFGJm5eYF9EcH4jDBHehn5aAIAIb9eCLQ/ImWFgSOHx8vTk4/ssckTUBlQbYJPf5MFgGr/wcBShOQ5E+dO5y3jYe0F5nP/jswKagj9/LxCT4oxI/vDA1a1BTF063I+vPhO2Miz4b+0ZsH2aYcT5RQwYhzhsmiDYfD+1CITkAfYOrm8LvPYOdsAwy+iqP6zN6ZhPlkMZug8gwoXI8Q7p3ghxtKrX5QwmFF7W6SOKan/GHh7s3bT8/e7s9kCy/uyvpUY8VmojdFTc+Pb7FHwmj3VO9iNIQcsqtPZpfUf+20yfNwHphp0VdO8WHqTBH3L+7NOiICcRvY8DNCRiXGn8CwBdPufYFyILgYcNnIpauz28E6GbldWpBVrWZmbdvGVAz9gb6GI1mWeYvx5RpW2e3oqDRFW0CdDQwT29SQA1DqeIcV3n63p1OiX706gqcqWVeFXxDp7pWSXZ5zUskE4fkB+OvKKl7Y3aH1PnC/fqZLIonFWomTJOD8xp88iVxPxsHuoHGCi9hO4LegcCpuYbV1FiwqI="
